Updated readme. Removed appending feature and added error checking for call to make. Also added line number to test results.

diff --git a/tester b/tester
--- a/tester
+++ b/tester
@@ -5,28 +5,18 @@ parent=${PWD%/*/*} # TODO not sure why I ha to add this opposed to using ~
 
 writeusage () {
     echo
-    echo "tester - UCSD CSE30"
-    echo "Makes and tests your program simultaneously with the sample program."
-    echo "The differences in stdout/stderr are shown in a vimdiff."
+    echo "      tester - UCSD CSE30"
+    echo "      Makes and tests your program simultaneously with the sample program."
+    echo "      The differences in stdout/stderr are shown in a vimdiff."
     echo
-#echo "Usage: tester [program] [solution program] [test input | --no-input]"
-    echo "Usage: tester [program] [solution program] [args]"
+    echo "      Usage: tester [program] [solution program] [filename]"
     echo
-    echo "Be sure to run this in a \"pa#\" directory."
+    echo "      Be sure to run this in a \"pa#\" directory."
     echo
 }
 
-# This checks if the user would like to continue adding to an existing
-# solution file. TODO We may want to make this a command line instruction.
-echo
-echo "Would you like to append to solution files? [y/n] "
-read rmSolfiles
-
-# This is the command to read from terminal --> read rmdatafiles
-
 # If the user doesn't know how to use this
-# TODO We may need to change the number of arguments
-if [[ "$#" < 2 ]]; then
+if [[ "$#" < 3 ]]; then
     writeusage
     exit 1
 fi
@@ -42,37 +32,70 @@ soldriver="$1"
 sample_prog="$parent/public/$soldriver"
 shift
 
-# Second arg is the input (or lack thereof)
-# if [[ "$1" != "--no-input" ]]; then
-#     src="cat $PWD/$1" # This opens the file
-# fi
-# shift
-
-# The rest of the arguments are passed to the driver
-# This needs to be 
-while [[ "$#" > 0 ]]; do
-     args="$args $1"
-     shift
-done
+#Third arg is the text file
+input="$1"
+shift
 
 # Make your file
 # This makes the default target
-make
+if !make;then
+    echo "      **********************************************"
+    echo "      *        Make failed!! Exiting script.       *"
+    echo "      **********************************************"
+    echo "                    ~Sorry Dude :( ~"
 
-# Remove and recreates apropriate files
-if [ "${rmSolfiles,,}" != "y" ]; then
-    rm -f mine sol
+    #Quit script
+    exit 1
 fi
 
-echo "Attepting to run loacal driver..."
-# Create output file taking in stderr & stdout
-# This is is what we should probably run in a loop
-$my_prog$args >> mine 2>&1 && echo "Running $my_prog$args..."
+count=0	      # Count the number of tests performed
+passedCount=0 # Count the number of tests passed
+OLD_IFS=$IFS  # Save the delimiter
+IFS=$'\n'     # Make the delimiter a newline
 
+# Get lines from file
+for line in $(cat $input)
+do
+    # Reset delimiter 
+    IFS=$OLD_IFS
 
-echo "Attempting to run solution..."
-# Save solution output
-$sample_prog$args >> sol 2>&1 && echo "Running $sample_prog$args..."
+    let count++
+    count_msg="TEST: $count\n"
+    echo $count_msg
+
+    # number test in file to make the results easer to understend
+    echo $count_msg >> mine
+    echo $count_msg >> sol
+
+    # Read arguments
+    args=""
+    for num in $line; do
+        args="$args $num"
+    done
+
+    # Create output file taking in stderr & stdout
+    echo "      Attempting to run $my_prog$args ..."
+    $my_prog$args > mine 2>&1 \
+        && echo "      Running $my_prog$args...\n"
+
+    # Save solution output
+    echo "      Attempting to run $sample_prog $args..."
+    $sample_prog$args > sol 2>&1 \
+        && echo "      Running $sample_prog$args...\n"
+
+    if [ "`diff mine sol`" = "" ]; then
+        let passedCount++
+    fi
+
+    IFS=$'\n'
+
+done < $input
+
 
 # Compare output files
+echo $passedCount/$count tests passed.
+echo "Would you like to see the diff file? [y/n]"
+read continueKey
+if [ "${continueKey}" = "y" ]; then
 vimdiff mine sol
+fi
